name: Android Build Workflow

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        type: choice
        options:
          - 'assembleRelease'
          - 'rebuildApk'
        default: 'rebuildApk'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: (cd Hydrogen && chmod +x gradlew)

      - name: Execute Gradle Command in Hydrogen Directory
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "assembleRelease" ]; then
            (cd Hydrogen && ./gradlew app:assembleRelease)
          elif [ "${{ github.event.inputs.build_type }}" = "rebuildApk" ]; then
            (cd Hydrogen && ./gradlew app:rebuildApk)
          fi

      # 调试步骤：仅当构建类型为 assembleRelease 时检查路径
      - name: Debug assembleRelease Path
        if: github.event.inputs.build_type == 'assembleRelease'
        run: |
          echo "---- assembleRelease APK 路径验证 ----"
          ls -la Hydrogen/app/build/outputs/apk/release/

      # 调试步骤：仅当构建类型为 rebuildApk 时检查路径
      - name: Debug rebuildApk Path
        if: github.event.inputs.build_type == 'rebuildApk'
        run: |
          echo "---- rebuildApk 自定义路径验证 ----"
          ls -la Hydrogen/app/build/outputs/custom-apk/

      # 上传 assembleRelease 产物
      - name: Upload Release APK
        if: github.event.inputs.build_type == 'assembleRelease'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            Hydrogen/app/build/outputs/apk/release/*.apk
            Hydrogen/app/build/outputs/mapping/release/mapping.txt

      # 上传 rebuildApk 产物
      - name: Upload Rebuilt APK
        if: github.event.inputs.build_type == 'rebuildApk'
        uses: actions/upload-artifact@v4
        with:
          name: rebuild-apk
          path: |
            Hydrogen/app/build/outputs/custom-apk/*.apk
            Hydrogen/app/build/outputs/mapping/release/mapping.txt